### ISSUE TITLE
Feature Request: Make the labels on the sorting algorithm clickable

### ISSUE THREAD

**Issue by Solo-Coder** [JakubSteplowski/devRantUnofficial#10]
The sorting algorithm consists of 3 radio buttons. To change them, you have to click exactly on it. If you push on the button's label, nothing happens. This is not a problem for big screens like computers, but on smaller screens like phones, it makes it easier to click on them.

**Comment by JakubSteplowski** [comment]
Done!

Will be available in v2.0.0-beta03, released in a few hours.
