### ISSUE TITLE
Acrylic material for title bars

### ISSUE THREAD

**Issue by ghost** [JakubSteplowski/devRantUnofficial#11]
The main panel title bar (bar with notifications/rant sort and filter) already has acrylic material. News/weekly box, rant filter panel and user title panel should have it too

**Comment by JakubSteplowski** [comment]
Will be done in a future build. :)

**Comment by JakubSteplowski** [comment]
Unfortunately I can't find a way to make it look good.
Too much blur, which simply doesn't look good on these panels.

![devrant-unofficialuwp-fluent-test](https://user-images.githubusercontent.com/4522930/41414701-12b7ce62-6fe7-11e8-9b63-bdede3b2b663.gif)

Maybe in the future with another type of layout it will be possible.
