### ISSUE TITLE
Suggestion: Bigger "Send Rant" button on Desktop

### ISSUE THREAD

**Issue by Raamakrishnan** [JakubSteplowski/devRantUnofficial#14]
Can you make the "Send Rant" button big on Desktop, maybe by adding a Send text next to it. And the Save button on the Change username page too.
![screenshot 8](https://user-images.githubusercontent.com/9772489/32402331-6b310f3a-c147-11e7-9795-da532910ff8f.png)
![screenshot 9](https://user-images.githubusercontent.com/9772489/32402333-7beae30a-c147-11e7-9396-b4e8ccb6c1a6.png)

**Comment by JakubSteplowski** [comment]
Nice idea :)

**Comment by JakubSteplowski** [comment]
Done!

- Avatar Builder Page (Save button)
- Edit Account Page (Save button)
- Edit Comment Page (Save button)
- Edit Profile Page (Save button)
- Edit Rant Page (Save button)
- Notifs Page (Clear button)
- Post Rant Page (Post button)
- Profile Page (Edit button)
