### ISSUE TITLE
Feature Request: Add chronological sorting on rant comments

### ISSUE THREAD

**Issue by Solo-Coder** [JakubSteplowski/devRantUnofficial#15]
Sometimes when we are subscribed to an active rant we want to check whether there are new comments on it. Currently, the only ways that's possible to do that is by being on the most recent rant and drag downwards for reload or do the same thing on top of a rant. However, this way you lose track of the rant and/or of the comment, especially if there are many rants and comments (and not being subscribed of course). By adding a chronological sort "Oldest to Most Recent" and "Most Recent to Oldest", you facilitate the reloading and viewing processes.
Alternatively, you can just add a reload button on main view and rant view.

**Comment by JakubSteplowski** [comment]
Interesting feature suggestion, I need to find the better way to implement it, so it could arrive a bit later. :)

**Comment by JakubSteplowski** [comment]
It can cause confusion, and it's not a must have especially since there is the button to scroll to the bottom.
I have to focus on more important features at this moment (not a lot of free time), but thanks for the suggestion.
