### ISSUE TITLE
Bug: Opening tags on Desktop

### ISSUE THREAD

**Issue by nikola1402** [JakubSteplowski/devRantUnofficial#16]
On the desktop version of the app, clicking on rant tag in rant feed (left plane) will only work if the right plane is closed (empty). Once the right plane is filled with any content, tags in the rant feed stop working.

Clicking on tags in the right plane works just fine.

App version 2.0.0-beta05
OS W10pro 1703 build 15063.674

**Comment by JakubSteplowski** [comment]
Works just fine here:

![devrant-v2-tags](https://user-images.githubusercontent.com/4522930/32408555-4319a8b0-c19a-11e7-9406-9c873af14df1.gif)

Are you talking about this or maybe there is a particular case in which it doesn't work?

**Comment by nikola1402** [comment]
Here's how it looks on my screen:

![devrant](https://user-images.githubusercontent.com/29949083/32408716-bcbc1a60-c19d-11e7-886b-9e9107c14a59.gif)


Clicking on rants and tags in rants that are opened in the right plane work fine.
When the right plane is populated with content, the tags in the feed (left side) stop working.

If you can't see it in this gif, i'll record another one.
There is no special case scenario, i tried different themes, resizing the screen, and it still works like this

**Comment by JakubSteplowski** [comment]
Ok, so the problem is that you can't search a tag if you're already in the Search Page.

I will work on a fix. ;)

**Comment by nikola1402** [comment]
That would be it :)
I'm not sure if it will be important, but:
Since it remembers the pages/rants you've previously read, it remembers the search page also. So you have to click on Back button until you get past the Search in order for it to work again. 

![devrant2](https://user-images.githubusercontent.com/29949083/32408846-19d29de4-c1a0-11e7-925c-9da0dc619e6b.gif)

Hopefully it's the same fix, and thanks for the quick response :)

**Comment by JakubSteplowski** [comment]
Already found a fix.

It's more a "workaround", since it doesn't remember the past search, so you if you click on a new tag you lost the previous one.
I don't thing it's a big problem, maybe in future I will implement a search history. :)

**Comment by nikola1402** [comment]
Nice, that was fast!
Since you're so dedicated, one aesthetic feature suggestion coming right up for future considerations :)

**Comment by nikola1402** [comment]
Hey man, just got the update. It works fine now when I'm on the search page, but when I open a rant from that search page, the problem appears again :/ It overrides the search only while I'm on search page.
Take a look at my comment with second gif i posted.
Sorry if i wasn't clear enough...

Here's another gif with latest version:

![devrant3](https://user-images.githubusercontent.com/29949083/32410417-bd51910e-c1bf-11e7-8d35-cbfe50912357.gif)

Do you need me to open a new issue for this?

**Comment by JakubSteplowski** [comment]
That's bad... :\

I'll search the reason in these days.
Maybe today.

**Comment by nikola1402** [comment]
One issue at a time :)

**Comment by JakubSteplowski** [comment]
Fixed. :)
Will be present in the public beta today/tomorrow.

**Comment by nikola1402** [comment]
Great work! :)
