### ISSUE TITLE
Suggestion: Wider scrollbars for desktop

### ISSUE THREAD

**Issue by Raamakrishnan** [JakubSteplowski/devRantUnofficial#18]
Consider making the custom scrollbars wider on mouseover. It makes them more accessible by mouse. Or consider shifting to the default scrollbars

**Comment by JakubSteplowski** [comment]
I will probably make it wider, but the default one is too wide, it looks very bad with this kind of apps (it looks ok only in web browsers).

**Comment by Raamakrishnan** [comment]
I feel like Wider only on mouseover, like the default scrollbar, will look good.
It is your call :)

**Comment by JakubSteplowski** [comment]
I'm not sure it's something possible.
The size of the scrollbar is static, which means it's loaded once, so I can't make it wider only on mouseover.

**Comment by Raamakrishnan** [comment]
I am not sure how you implemented your scrollbar, but if it is just a styled version of the default scrollbar, it has 2 different visual states: `TouchIndicator` and `MouseIndicator`. And you can see in this default style https://msdn.microsoft.com/en-in/library/windows/apps/mt299150.aspx?f=255&MSPPError=-2147217396 how they have implemented the switch between the two.

**Comment by JakubSteplowski** [comment]
Ok, didn't notice that. :)

Thanks!

**Comment by JakubSteplowski** [comment]
I restored the default scrollbar.

Will be available in v2.0.0-beta4.
