### ISSUE TITLE
devRant 2.0 crashes on startup (on Anniversary Update)

### ISSUE THREAD

**Issue by Solo-Coder** [JakubSteplowski/devRantUnofficial#2]
When I tap the app icon, the devRant logo appears and then the app crashes.

Device: Microsoft Lumia 535
Version: 1607
OS build: 10.0.1.14393.1358

**Comment by JakubSteplowski** [comment]
Working on a fix.

I sent you a private email. :P

**Comment by Solo-Coder** [comment]
The app seems to have installed, but it still crashes on start up. Are you on the discord server or maybe add me on Skype for quicker communication?

**Comment by JakubSteplowski** [comment]
@dkalets send me your skype username via email. :)

**Comment by JakubSteplowski** [comment]
@dkalets of course via email, not on skype. 😅

**Comment by JakubSteplowski** [comment]
I'm removing the support for Anniversary Update (it should happen in the next hours), so the beta testers on that OS version will receive only the stable builds (v1.5.7, v.1.5.8) until I'll fix this.

**Comment by JakubSteplowski** [comment]
**v2.0.0-beta9** with support for Anniversary Update has been submitted to the store.
