### ISSUE TITLE
Option to remove two column view

### ISSUE THREAD

**Issue by cozyplanes** [JakubSteplowski/devRantUnofficial#21]
I have a big screen (2k monitor) and having the rant view, in the left side is annoying...

Can you make the theme as following?
Acrylic material as bg, put white/black text above it. 
And make the rant view consume the whole screen

**Comment by cozyplanes** [comment]
sorry if it is like a change only for me

**Comment by JakubSteplowski** [comment]
I will add an option to hide the left side when you open a rant. ;)

**Comment by cozyplanes** [comment]
is there a way to completely disable the 2 column view and replace with 1 column view like in v1.x.x ?

**Comment by JakubSteplowski** [comment]
I think it looks worse, but I can implement this...

**Comment by JakubSteplowski** [comment]
Done! :)

The ability to activate the "One Column View" mode will be available in v2.0.0-beta5 in a few hours.
