### ISSUE TITLE
Sidebar hidden when not in Main view

### ISSUE THREAD

**Issue by Solo-Coder** [JakubSteplowski/devRantUnofficial#24]
The sidebar is only shown on the Main view of the app. Going to another view hides it and the options to go back are either a Close button (Swag, Supporters, Settings, Feedback, About) or a Back button (all the rest). The problem is if people juggle too many times from notifs to rants, it requires too many times to click the Back button to go to the Main view.

**Comment by JakubSteplowski** [comment]
What do you mean exactly?
You're talking about the Menu or about a way to go back to the Main View when you're in Rant View?

![immagine](https://user-images.githubusercontent.com/4522930/32499888-1e72337e-c3d4-11e7-8e6b-e5e055d90c60.png)

**Comment by Solo-Coder** [comment]
I'm talking about clicking between "Notifs" and "There are new comments on a rant you commented on" (for example) about 15 times and then going back to the Main screen requires to press Back 30 times.

**Comment by JakubSteplowski** [comment]
@dkalets ok, so rants opened through Notifs View shouldn't be added to the navigation stack?
It's something I can do. ;)

**Comment by Solo-Coder** [comment]
That could work, but you're adding more clicks in certain use cases (and maybe more complex code).

Example Use Case: Make a Search after visiting a Rant from Notifs:
1. Click Notifs
2. Click the Rant
3. Click Back (now to Notifs view)
4. Click Back (now to Main view)
5. Click Search

While if you had the Sidebar on it would be like:
1. Click Notifs
2. Click the Rant
3. Click Search

**Comment by JakubSteplowski** [comment]
I can add it on desktop, but on Mobile it will look strange.
Anyway, I will try to find a solution to this. :)

Thanks for your suggestion!

**Comment by Solo-Coder** [comment]
It's on the mobile that should be implemented. On desktop there's a 2 column view so far, so everything are shown.
Also what do you mean by strange on Mobile? Just add a hamburger button on top left corner just like in v1! ;)

**Comment by JakubSteplowski** [comment]
Never had the time to implement it, sorry for that.
I started to focus on v3, which probably won't be available for Windows 10 Mobile (at least I can tell you already that it won't be available for Anniversary Update).
I hope Microsoft will release some sort of new mobile device in future (Andromeda?), but until then my main focus are PC, Xbox and HoloLens.
