### ISSUE TITLE
Settings > Muted Notifs "NULL"

### ISSUE THREAD

**Issue by 7twin** [JakubSteplowski/devRantUnofficial#25]
I am not sure if that is a bug or not, but in the settings there is just the devrant icon with "NULL" under it in the muted notifications section.

Win10 1709

**Comment by JakubSteplowski** [comment]
It's not a bug. :P

It means you didn't mute any rant.
To mute one, you just need to open it and it the menu (top right corner) select "Mute notifs from this Rant". 
(of course this mute just locally the notifs from it, it's not a server side action).
