### ISSUE TITLE
Error when refreshing a rant and icon

### ISSUE THREAD

**Issue by 7twin** [JakubSteplowski/devRantUnofficial#29]
This occured when I refreshed a rant via pull-to-refresh and there was no internet connection problems nor was devrant down also the icon has a small line that makes the circle appear less smooth on the inside:

![image](https://user-images.githubusercontent.com/32747235/32506896-14636512-c3e6-11e7-89a5-1f9913b26e26.png)

**Comment by JakubSteplowski** [comment]
Can you link the rant?

**Comment by 7twin** [comment]
I sadly don't remember what rant it was, but it happened later with other 2 again just randomly, most often I have to go back and visit the rant again and it works fine. I'll try to paste the next time it happens the rant link here.

**Comment by JakubSteplowski** [comment]
It is very strange if the rant works great before the refresh and when you retry to refresh it.
The app does the same things every time, so it seems more like a temporary (very short) internet or devRant servers problem.

If the rant didn't work it could be fault of the JSON parser, but it worked when you retried, so it isn't.

Anyway, when occurs, link it here (or at least the nickname of the user, to be able to find it).

**Comment by JakubSteplowski** [comment]
I fixed the error icon glitch.

If the other problem happened again, write it here.
