### ISSUE TITLE
Ellipsis menu flyout overlapping with Window controls

### ISSUE THREAD

**Issue by Raamakrishnan** [JakubSteplowski/devRantUnofficial#3]
The ellipsis menu flyout on the top right, when opened, overlaps with the window controls. Maybe `Placement="Bottom"` will work?

![screenshot 3](https://user-images.githubusercontent.com/9772489/32245816-00a286d6-bea3-11e7-8c1f-cf08216e6fe0.png)

**Comment by JakubSteplowski** [comment]
Another glitch I will try to fix in the next closed beta build. :)

**Comment by JakubSteplowski** [comment]
Fixed!

I will release soon an update for beta testers! :)

![screenshot_1](https://user-images.githubusercontent.com/4522930/32278445-12f70dfc-bf16-11e7-9892-ab9b87e8849f.png)

**Comment by Raamakrishnan** [comment]
This issue is also affecting the User Profile page
![screenshot 7](https://user-images.githubusercontent.com/9772489/32402365-05f623d4-c148-11e7-8349-e7a95c7e46aa.png)

**Comment by JakubSteplowski** [comment]
I forgot to fix this in other parts of the app...

Thanks for the report!

**Comment by JakubSteplowski** [comment]
Fixed, v2.0.0-beta05 will be out soon.
