### ISSUE TITLE
Run in background for notifications

### ISSUE THREAD

**Issue by 7twin** [JakubSteplowski/devRantUnofficial#30]
A nice feature would be to minimize the app to a trayicon so you could always have live notifications, without having it open all the time or minimized.

**Comment by JakubSteplowski** [comment]
Push notifications will arrive in one of the future updates, so this problem will be solved. ;)

At this moment you need to refresh the feed (or scroll to the bottom to see new rants) or go to the Notifs Page to check if new arrived.
