### ISSUE TITLE
Refreshing content

### ISSUE THREAD

**Issue by 7twin** [JakubSteplowski/devRantUnofficial#31]
v2.0.0-beta3

If you are deep down a rant with its comments, there is no refresh function, maybe add one in the top next to the share icon and or allow F5 to refresh the content? also maybe scroll to the exact same position after refreshing, so it wouldn't reset to the very top either.

**Comment by JakubSteplowski** [comment]
Now you can scroll to top and pull to refresh.
But I understand that it's not very handy.

I will surely add support for some keybinds, like F5 to refresh in near future, but maybe I will add something to refresh also when you're on Mobile.

**Comment by JakubSteplowski** [comment]
I added a refresh button at the bottom if a rant has more than 3 comments (will be present in the next update, v2.0.0-beta6), and with the future F5 key support the problem will be solved completly. :)
