### ISSUE TITLE
Icons are invisible with transparency turned off

### ISSUE THREAD

**Issue by 7twin** [JakubSteplowski/devRantUnofficial#32]
So this problem can be solved by just deactivating fluent design in the options, but it's still a bug, if one deactivates transparency in windows, keeps the fluent design option in the client turned on, has a white windows theme and then goes focuses the app - the icons turn invisible, because they are white on white.

**Comment by JakubSteplowski** [comment]
I don't understand why someone should turn off the transparency on Windows, but yes, it's a bug I never noticed (because I never turn the transparency off).

Thanks for the report!

**Comment by JakubSteplowski** [comment]
This bug has been finally fixed.
A new update will arrive soon.
