### ISSUE TITLE
Notification Counter font too small

### ISSUE THREAD

**Issue by 7twin** [JakubSteplowski/devRantUnofficial#33]
First of all thanks for implementing the font feature, but it doesn't affect the notification counter, which is still too small to read.

**Comment by JakubSteplowski** [comment]
I hope now is big enough.

Before:
![immagine](https://user-images.githubusercontent.com/4522930/32851910-b04a8950-ca36-11e7-92fe-d5c4e80d2176.png)

After:
![immagine](https://user-images.githubusercontent.com/4522930/32851908-acafc710-ca36-11e7-8be5-4d5745f9fa1a.png)
