### ISSUE TITLE
Rant/Comments Filters

### ISSUE THREAD

**Issue by 7twin** [JakubSteplowski/devRantUnofficial#35]
A function to filter rants and comments by keywords or nicknames.

**Comment by JakubSteplowski** [comment]
Would you like to see only rants of a few users, or don't see rants of a few users (black/white list)?

In both cases it's a bit discriminatory, and antisocial.
You can already subscribe to users' rants and receive a notification when they post.

Speaking about keywords, you can already search rants.

Dfox said that he will implement in future more search options and there will be also a rant type filter (rants/stories, jokes/memes, questions, devRant releated posts, and random).

The other reason why I'm skeptical about these suggestions is that there isn't a way to do it in the API, and would be forced to do it locally (just don't show that kind of rants, but your phone would be still forced to download all of them).

Imagine a case where the rant which meets the requirements of the filter isn't present on any of the first 10 pages of the devRant feed, but only on 11th page.
This means that your phone has to download 11 pages (220 rants in total) to show you just 1 rant.
And if we want to fill 1 single page, it has to find 20 rants that meet the requirements.

When it should stop to search for them?
The 20 rants could be spread over 200-1k pages (4k-20k rants), or just don't be present at all (there are about 115k rants in total, should it search through all of them?).
And so on for every page.

It's just impossible, at least right now, sorry.
