### ISSUE TITLE
Edit/Modify Dialog is off center

### ISSUE THREAD

**Issue by Raamakrishnan** [JakubSteplowski/devRantUnofficial#4]
Screenshot:
![screenshot 4](https://user-images.githubusercontent.com/9772489/32246192-3366c9be-bea4-11e7-9d20-c0bdd88867a6.png)

**Comment by JakubSteplowski** [comment]
Thanks for the report!

I will try to fix it in the next closed beta build.

**Comment by JakubSteplowski** [comment]
Fixed!

I will release an update for beta testers soon! :)

![screenshot_2](https://user-images.githubusercontent.com/4522930/32278728-e20760d8-bf16-11e7-8440-c422ecb6ff56.png)
