### ISSUE TITLE
On Desktop, clicking multiple links on a user page crashes app

### ISSUE THREAD

**Issue by rekonnected** [JakubSteplowski/devRantUnofficial#41]
Found a bug on Desktop. If you go to a user who has more than one web link on their page and click the set of links, the app crashes completely.

**Comment by rekonnected** [comment]
Realized that an issue was already there and closed. Oops. :/

**Comment by JakubSteplowski** [comment]
#39 

The fix will be available in v1.5.13 (Feb/Mar) for Anniversary Update and older builds, and a few weeks later in v2.0.0-beta8 for Creators Update and newer builds.
