### ISSUE TITLE
Not showing the iconic maintainance rant

### ISSUE THREAD

**Issue by cozyplanes** [JakubSteplowski/devRantUnofficial#42]
jsRant shows well
![](https://i.imgur.com/39z2ARj.png)

But in devRant UWP it says internal error/network connection error

**Comment by JakubSteplowski** [comment]
Most likely that rant is missing the "user_id" parameter, or something different, that causes an exception.
I will contact dfox and will fix this when possible.

**Comment by cozyplanes** [comment]
`!important == true`
