### ISSUE TITLE
Remove "buy custom avatar stickers" in avatar menu

### ISSUE THREAD

**Issue by cozyplanes** [JakubSteplowski/devRantUnofficial#43]

**Comment by cozyplanes** [comment]
@JakubSteplowski Remove this as well in swag page
![](https://i.imgur.com/rjHy6yx.png)

**Comment by JakubSteplowski** [comment]
@cozyplanes the items in the Swag Page are fetched directly from devRant (and for this reason you can find it also on the official Android and iOS clients), so dfox have to update them on the server, I can't do it.

**Comment by cozyplanes** [comment]
@JakubSteplowski From where do you fetch data? I don't see them in swag store/free stickers page

**Comment by JakubSteplowski** [comment]
@cozyplanes it's top secret...
But I'll tell you anyway: 
https://devrant.com/app-pages/store-products
As I said before, the official Android and iOS apps use the same source.

![immagine](https://user-images.githubusercontent.com/4522930/36316741-6d28560e-133b-11e8-8931-d5da91f17b94.png)

But you're right, it seems they are using a different source for this page (but it's something new):
https://devrant.com/free-stickers

**Comment by cozyplanes** [comment]
So there are bunch of secret apis only YOU and the dfox know?(

**Comment by cozyplanes** [comment]
@trogus is overhauling the web version so i think he is changing everything

**Comment by JakubSteplowski** [comment]
Removed in stable v2.0.0 (or v2.0.0-beta13 if it will exist).

**Comment by JakubSteplowski** [comment]
I had to make some changes in the still unreleased v2.0.0-beta12, which means these changes will be already there.
