### ISSUE TITLE
Make these textbox NOT multiline

### ISSUE THREAD

**Issue by cozyplanes** [JakubSteplowski/devRantUnofficial#44]
1. Signup page
- username
- email
2. login page
- username
3. reset page
- email

**Comment by JakubSteplowski** [comment]
Thanks for this super detailed report!
I will fix this in v1.5.13 and v2.0.0-beta9. 😄

**Comment by cozyplanes** [comment]
That's freaking fast!

**Comment by JakubSteplowski** [comment]
@cozyplanes I have github always open. 😆

**Comment by cozyplanes** [comment]
I think you are a robot.

**Comment by JakubSteplowski** [comment]
It could be. 🤖

**Comment by cozyplanes** [comment]
@JakubSteplowski put the tags in #45

**Comment by JakubSteplowski** [comment]
Fixed in stable v2.0.0 (or v2.0.0-beta13 if it will exist).

**Comment by JakubSteplowski** [comment]
I had to make some changes in the still unreleased v2.0.0-beta12, which means these changes will be already there.
