### ISSUE TITLE
Accept enter (return) key as button clicked

### ISSUE THREAD

**Issue by cozyplanes** [JakubSteplowski/devRantUnofficial#45]
Allow enter (return) key press to login in login page / signup page / reset page

**Comment by cozyplanes** [comment]
@JakubSteplowski

**Comment by JakubSteplowski** [comment]
Yep, this is something I need to implement along with this #1.

**Comment by cozyplanes** [comment]
Another two!

**Comment by JakubSteplowski** [comment]
Finally implemented in v2.
The update we'll be available soon.
