### ISSUE TITLE
Broken Swag Page informations

### ISSUE THREAD

**Issue by cozyplanes** [JakubSteplowski/devRantUnofficial#47]
![](https://i.imgur.com/dVdqmAx.png)

**Comment by JakubSteplowski** [comment]
Wow.
I was sure this would happen one day, but not so fast... I implemented the function to get the updated data in v2.0.0-beta8 (#40).

I didn't find a way to get this information from the API (and dfox didn't respond to my answer on how to get them), so I implemented the easiest way (but as you can see far from perfect).
It gets the data from https://devrant.com/free-stickers but a simple change of the content of that page can break it (and it just happened).
I will try to find a workaround for this.

**Comment by cozyplanes** [comment]
That's what you call `fail`.
Just hardcode 20 and 500 to that.

I think it won't change any time soon(TM)

**Comment by JakubSteplowski** [comment]
@cozyplanes I thought about that, but imagine if someone will see "20 and 500" in future, now they are true, but in future could be completly false, so I think it's better to show a simple "N/A" and make the user click on the "Learn more" button which will show you the official page with updated info.

**Comment by JakubSteplowski** [comment]
Fixed in v2.0.0-beta14.
