### ISSUE TITLE
Move feedback stuff to about > what's next

### ISSUE THREAD

**Issue by cozyplanes** [JakubSteplowski/devRantUnofficial#48]
Move this : 
![](https://i.imgur.com/18sfXK7.png)

to : 
![](https://i.imgur.com/JEOIqql.png)

**Comment by cozyplanes** [comment]
Official unofficial.......

WTF?????

**Comment by cozyplanes** [comment]
@JakubSteplowski

**Comment by JakubSteplowski** [comment]
It must to be visible for everyone, so moving it entirely to the About page could prevent the user to know that there is the ability to report issues.

The other reason is that the "What's Next" section could not exist in future...

**Comment by cozyplanes** [comment]
ok then

1. that white makes my eyes pop out. please don't do that.
2. too big
3. official unofficial.... need to rephrase
@JakubSteplowski

**Comment by JakubSteplowski** [comment]
@cozyplanes 
Ok, I will redesign that page in future.
