### ISSUE TITLE
Glow effect not displaying corrently in Lumia 950

### ISSUE THREAD

**Issue by Telescuffle** [JakubSteplowski/devRantUnofficial#5]
Glow effect showing very harshly on Lumia 950. For example, on the 'To top of page' navigation arrow, there is just a solid circle of light around the button which doesn't soften over distance. I cannot screenshot the issue, but may be an issue with AMOLED displays. 
![wp_ss_20171031_0005](https://user-images.githubusercontent.com/9273260/32246619-7aa2640a-be77-11e7-87c4-1b2fa8a320ad.png)

**Comment by JakubSteplowski** [comment]
It's a shadow, but when it works pretty well on Light theme, on Dark and Blacks it looks weird.
I need to find something different.

**Comment by Telescuffle** [comment]
Hmmm. It's no problem. Am just being picky. It's barely noticeable with the dark theme. You will only notice if you look for it. 

Is the idea for it to be drop shadow in order to give it depth?

**Comment by JakubSteplowski** [comment]
@Telescuffle yes.

**Comment by Telescuffle** [comment]
Maybe for now just disable for dark modes? Something which has no light on it cannot cast a shadow after all.

**Comment by JakubSteplowski** [comment]
Probably will do.
Same for other drop shadows (rant image, avatars, others on Desktop).

**Comment by Telescuffle** [comment]
Been looing around at other apps but Groove does some sort of colour glow based on the image: 
![image](https://user-images.githubusercontent.com/9273260/32267671-fb0dac3c-bee3-11e7-9117-360855864cc8.png)

Where by i think soundbyte does something similar to you. 
![image](https://user-images.githubusercontent.com/9273260/32267753-383fca40-bee4-11e7-8acf-e8e4536ee0cb.png)

**Comment by JakubSteplowski** [comment]
Removed drop shadow on dark themes. :P

An update for beta testers will be available soon.

![screenshot_3](https://user-images.githubusercontent.com/4522930/32279103-02f2bf58-bf18-11e7-999b-72425756190b.png)
