### ISSUE TITLE
devBanner generate option in app

### ISSUE THREAD

**Issue by cozyplanes** [JakubSteplowski/devRantUnofficial#51]
Please consider adding devbanner generate option in app

link:     
https://generator.devbanner.center/banner?username=Username&subtext=Your%20subtext%20here&width=800

 For the width, min value is 128, max value is 2048, default is 800

**Comment by JakubSteplowski** [comment]
Is this service still active?
The link provided doesn't work anymore, and I can't generate a banner even using the official website.

**Comment by cozyplanes** [comment]
No, seems that kimmax has the frontend running but the backend is down
I can move the service to azure, but that would cost me a lot, so I can say the project is abandoned
