### ISSUE TITLE
@ list blending with background

### ISSUE THREAD

**Issue by cozyplanes** [JakubSteplowski/devRantUnofficial#53]
![image](https://user-images.githubusercontent.com/25971070/42830344-17082904-8a26-11e8-9224-bb657c52d030.png)

In dark theme, the @ list mixes with the background making it hard to see

**Comment by cozyplanes** [comment]
happens in white theme too
maybe making the @ list bg non-transparent?

**Comment by JakubSteplowski** [comment]
It's definitely a bug.
It happens if you disable the "Fluent Design" in the settings, I forgot to put a background for that setting.

Just enable "Fluent Design" until a new update. Thanks.

**Comment by cozyplanes** [comment]
@JakubSteplowski gottcha

**Comment by JakubSteplowski** [comment]
The fix will be present in v2.0.0-beta16 later this week.
