### ISSUE TITLE
Strange gap between @ list and comments input box

### ISSUE THREAD

**Issue by cozyplanes** [JakubSteplowski/devRantUnofficial#54]
![image](https://user-images.githubusercontent.com/25971070/42830574-c90f79ae-8a26-11e8-86ea-58af93c7c84f.png)

**Comment by JakubSteplowski** [comment]
It's not a bug, it's a feature. 😂

They are two different panels. The margin is also present on the sides. 😜

**Comment by cozyplanes** [comment]
A little-bit disturbing for me btw

**Comment by JakubSteplowski** [comment]
Will see how it looks without it.

Maybe I'll change it. 😉
