### ISSUE TITLE
Show usernames in batches when there are usernames written in rant with @

### ISSUE THREAD

**Issue by cozyplanes** [JakubSteplowski/devRantUnofficial#57]

**Comment by JakubSteplowski** [comment]
What do you mean exactly?
Could you create a simple visual concept (even using paint) on how you imagine it?

Thanks in advance!

**Comment by cozyplanes** [comment]
People type usernames with the @ in rants, and other ranters come in saying mentions doesn't work in rants.
Maybe add an option to automatically post a comment with mentions, or give a heads-up

**Comment by JakubSteplowski** [comment]
Cool idea!
Will add the option to post automatically a new comment.

**Comment by JakubSteplowski** [comment]
The automatic comments with the mentioned users will be available in the next update.
