### ISSUE TITLE
Hamburger Menu is unreadable in Tablet mode.

### ISSUE THREAD

**Issue by prkhandelwal** [JakubSteplowski/devRantUnofficial#58]
The hamburger menu gets completely white and unreadable while using the app in Tablet mode.

**Comment by JakubSteplowski** [comment]
Hi!

Could you attach a screenshot?
And give more information: type of device, which theme are you using (it happens with a particular one or with all of them?), OS version, transparency on or off, etc.

I tried on my PC desktop and it seems ok:

![screenshot_1](https://user-images.githubusercontent.com/4522930/45916210-6546a080-be62-11e8-9b0c-37006a4c0f60.png)

But this can be different for devices with activated battery saver mode (when fluent design is seen as active for the app, but it isn't in the reality, so the color of the icons is the same as the background).

Maybe it's the same problem another user reported here: #32

Let me know, thanks!

**Comment by prkhandelwal** [comment]
![image](https://user-images.githubusercontent.com/12965931/45918139-f851fb80-be9f-11e8-850a-bd2b3795dcf7.png)

![image](https://user-images.githubusercontent.com/12965931/45918161-5ed71980-bea0-11e8-946c-5c9a548583dd.png)


I have dark theme enabled both on my system and on devRant. Transparency is switched on. I am on Windows 10 April Update.

Works perfectly on white theme on my system too.

**Comment by JakubSteplowski** [comment]
Thanks for the provided information.

I will work on a fix.

#32

**Comment by JakubSteplowski** [comment]
This bug has been finally fixed.
A new update will arrive soon.
