### ISSUE TITLE
Default theme according to system default app mode settings

### ISSUE THREAD

**Issue by Panda-Sharp** [JakubSteplowski/devRantUnofficial#59]
If I have my system default app mode settings to Light use a light theme
If I have my system default app mode settings to Dark use a dark theme

Thanks a lot for your work, keep going!

**Comment by JakubSteplowski** [comment]
Thanks for your suggestion!

I will try to find the time to implement it in the next release.

And yes, if you could please create a new issue for the sync on cloud feature request it would be better.

**Comment by JakubSteplowski** [comment]
This feature has been implemented in v2.0.0, available soon in the store. :)
