### ISSUE TITLE
Sync settings with the cloud

### ISSUE THREAD

**Issue by Panda-Sharp** [JakubSteplowski/devRantUnofficial#60]
Would be nice to sync settings with the cloud, for example if I download the app to a new pc it restore my settings (including theme). 

Thanks a lot for your work, keep going!

**Comment by JakubSteplowski** [comment]
It should be pretty simple.
I will try to include it in the next update! ;)

**Comment by Panda-Sharp** [comment]
>           It should be pretty simple.
> I will try to include it in the next update! ;)

yup...never used till now but should be
https://docs.microsoft.com/en-us/windows/uwp/design/app-settings/store-and-retrieve-app-data#roaming-data

**Comment by JakubSteplowski** [comment]
Exactly
