### ISSUE TITLE
Feature Request: Live Tile

### ISSUE THREAD

**Issue by Solo-Coder** [JakubSteplowski/devRantUnofficial#7]
With the new notifications coming to v2.0, it would be nice to take advantage of the Live Tiles.
It could either be just a badge number for the new notifs or
It could show the notif message (++ rant/comment, mention, new comments, new rants) and the corresponding icon, in a similar way of how messaging apps work.

**Comment by JakubSteplowski** [comment]
Thanks for the suggestion!

It's definitely something I will want to implement with the Push Notification support.
It will take a while to reach the stable build though, probably next year.

**Comment by Solo-Coder** [comment]
All good things take a while to develop! Making the app stable is more of a prio right now. :)

**Comment by JakubSteplowski** [comment]
A first version of live tiles (with notifs badge) will be present in v2.0.0-beta7. ;)

**Comment by Solo-Coder** [comment]
I can't wait for it! :D
