### ISSUE TITLE
Feature Request: Bigger image dimensions of rants

### ISSUE THREAD

**Issue by Solo-Coder** [JakubSteplowski/devRantUnofficial#9]
Some rants contain images. devRant lowers the resolution on the website feed by default but the resolution doesn't change. On the app, the images remain small. It should be nice and more readable if images scaled to their actual dimensions. (images attached with the app and web feed handling)
![example1](https://user-images.githubusercontent.com/5850664/32305573-fd96e644-bf7e-11e7-8feb-1e74981d6c16.png)
![example2](https://user-images.githubusercontent.com/5850664/32305576-fe6cb7c4-bf7e-11e7-9608-535eab52a1da.png)

**Comment by JakubSteplowski** [comment]
Just zoom in.
CTRL + scroll.

The default size is calculated at the moment based on the size of the window - a margin.
